<html>
<head>
    <title>Login</title>
</head>
<body>
<form action="/login" method="POST">
    <?php
    if (!empty($errors)): ?>
        <ul>
            <?php foreach ($errors as $field => $error): ?>
                <li><?=$error?></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <label for="email">Email:</label>
    <input id="email" type="text" name="email" placeholder="Email address"/>

    <label for="password">Password:</label>
    <input id="password" type="password" name="password" placeholder="Password"/>

    <input type="submit">
</form>
</body>
</html>