version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - '.:/var/www/html'
      - './deploy/nginx/conf.d:/etc/nginx/conf.d/'
    networks:
      - opt
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/html'
    networks:
      - opt
    depends_on:
      - mysql
  mysql:
    image: 'mysql:8.0'
    platform: "linux/amd64"
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - opt
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - opt
networks:
  opt:
    driver: bridge
volumes:
  mysql:
    driver: local
